### ISSUE TITLE
NoiseParameters is not public in MultiNoiseBiomeSource

### ISSUE THREAD

**Issue by EucloidMC** [LudoCrypt/MazeGenerationMod#1]
The code is working fine for the most part, I've included the API as a dependency. However, when checking for errors, all three "level" classes are giving this error, and if I ignore it and compile anyway, it just stops.

`'net.minecraft.world.biome.source.MultiNoiseBiomeSource.NoiseParameters' is not public in 'net.minecraft.world.biome.source.MultiNoiseBiomeSource'. Cannot be accessed from outside package`

**Comment by LudoCrypt** [comment]
Fixed in latest, use NoiseSettings
